### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by 4dvn** [NiklasRosenstein/movrepair#2]
Hi,

I have some mov file encrypted 150kb from header but moov atom still in file how can i repair this mov file via hexedit with reference file?

**Comment by NiklasRosenstein** [comment]
Hi @4dvn, if the file, or parts of it, are encrypted, you will not be able to recover the file contents without a decryption key. The code is for attempting to repair *corrupted* mov files, and this was mostly only successful if the only corrupted portion is in the file header.

**Comment by 4dvn** [comment]
> Hi @4dvn, if the file, or parts of it, are encrypted, you will not be able to recover the file contents without a decryption key. The code is for attempting to repair *corrupted* mov files, and this was mostly only successful if the only corrupted portion is in the file header.

I mean this method work for error mov,mp4,3gp,... and enceypted files
![image](https://user-images.githubusercontent.com/46510477/169133785-de582690-f64f-448d-8bf6-d05d277cf0ac.png)

**Comment by NiklasRosenstein** [comment]
Okay, I don't know what that is, but I recommend you to use this method then.
